import './globals.css';
import { Inter } from 'next/font/google';
import Sidebar from './components/Landign/sidebar';
import Footer from "./components/Landign/footer";  // Asegúrate de importar tu Sidebar

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-[#E6FAFF] to-white flex flex-col min-h-screen p-12 justify-center items-center`}>
        <div className="flex flex-col w-full">
          <div className="flex flex-1 overflow-hidden w-full shadow-xl rounded-2xl ">
            <Sidebar />
            <main className="flex-1 flex-col justify-start items-center p-6 bg-gray-200 rounded-r-lg overflow-auto w-full">
              {children}
            </main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
